PRICE_ADJUST_MODE = "gauss"
PRICE_ADJUST_CHANCE = 1
PRICE_ADJUST_MEAN = 1
PRICE_ADJUST_DEV = 0.5
PRICE_CONCESSION = PRICE_ADJUST_MEAN
MAX_PRICE = 50
AGENT_ID = 0

### SIM VARIABLES
WHEAT_KG_PRICE = 1.99 # Kg price
WHEAT_T_PRICE = 250 # Kg price
WHEAT_MIN_KG_BUY_QUANTITY = 25
WATER_PRICE = 0.00414 # Liter price

#### RECIPES
BREAD_FLOUR_NEEDED = 0.500
BREAD_WATER_NEEDED = 0.300
